nfl_teams = {
    "bears": "chicago bears",
    "chicago": "chicago bears",
    "chi": "chicago bears",
    "lions": "detroit lions",
    "detroit": "detroit lions",
    "det": "detroit lions",
    "packers": "green bay packers",
    "green bay": "green bay packers",
    "gb": "green bay packers",
    "pack": "green bay packers",
    "vikings": "minnesota vikings",
    "minnesota": "minnesota vikings",
    "min": "minnesota vikings",
    "vikes": "minnesota vikings",
    "falcons": "atlanta falcons",
    "atlanta": "atlanta falcons",
    "atl": "atlanta falcons",
    "panthers": "carolina panthers",
    "carolina": "carolina panthers",
    "car": "carolina panthers",
    "cats": "carolina panthers",
    "saints": "new orleans saints",
    "new orleans": "new orleans saints",
    "no": "new orleans saints",
    "who dat": "new orleans saints",
    "buccaneers": "tampa bay buccaneers",
    "bucs": "tampa bay buccaneers",
    "tampa bay": "tampa bay buccaneers",
    "tb": "tampa bay buccaneers",
    "cardinals": "arizona cardinals",
    "cards": "arizona cardinals",
    "arizona": "arizona cardinals",
    "ari": "arizona cardinals",
    "rams": "los angeles rams",
    "los angeles": "los angeles rams",
    "la": "los angeles rams",
    "49ers": "san francisco 49ers",
    "niners": "san francisco 49ers",
    "san francisco": "san francisco 49ers",
    "sf": "san francisco 49ers",
    "seahawks": "seattle seahawks",
    "hawks": "seattle seahawks",
    "seattle": "seattle seahawks",
    "sea": "seattle seahawks",
    "cowboys": "dallas cowboys",
    "dallas": "dallas cowboys",
    "dal": "dallas cowboys",
    "boys": "dallas cowboys",
    "giants": "new york giants",
    "gmen": "new york giants",
    "new york giants": "new york giants",
    "nyg": "new york giants",
    "eagles": "philadelphia eagles",
    "philly": "philadelphia eagles",
    "philadelphia": "philadelphia eagles",
    "phi": "philadelphia eagles",
    "commanders": "washington commanders",
    "washington": "washington commanders",
    "was": "washington commanders",
    "commies": "washington commanders",
    "ravens": "baltimore ravens",
    "baltimore": "baltimore ravens",
    "bal": "baltimore ravens",
    "bengals": "cincinnati bengals",
    "cincinnati": "cincinnati bengals",
    "cin": "cincinnati bengals",
    "who dey": "cincinnati bengals",
    "browns": "cleveland browns",
    "cleveland": "cleveland browns",
    "cle": "cleveland browns",
    "steelers": "pittsburgh steelers",
    "pittsburgh": "pittsburgh steelers",
    "pit": "pittsburgh steelers",
    "texans": "houston texans",
    "houston": "houston texans",
    "hou": "houston texans",
    "colts": "indianapolis colts",
    "indianapolis": "indianapolis colts",
    "ind": "indianapolis colts",
    "jaguars": "jacksonville jaguars",
    "jags": "jacksonville jaguars",
    "jacksonville": "jacksonville jaguars",
    "jax": "jacksonville jaguars",
    "titans": "tennessee titans",
    "tennessee": "tennessee titans",
    "ten": "tennessee titans",
    "broncos": "denver broncos",
    "denver": "denver broncos",
    "den": "denver broncos",
    "chiefs": "kansas city chiefs",
    "kc": "kansas city chiefs",
    "kansas city": "kansas city chiefs",
    "raiders": "las vegas raiders",
    "vegas": "las vegas raiders",
    "las vegas": "las vegas raiders",
    "lv": "las vegas raiders",
    "chargers": "los angeles chargers",
    "bolts": "los angeles chargers",
    "lac": "los angeles chargers",
    "dolphins": "miami dolphins",
    "fins": "miami dolphins",
    "miami": "miami dolphins",
    "mia": "miami dolphins",
    "patriots": "new england patriots",
    "pats": "new england patriots",
    "new england": "new england patriots",
    "ne": "new england patriots",
    "jets": "new york jets",
    "gang green": "new york jets",
    "nyj": "new york jets",
    "bills": "buffalo bills",
    "buffalo": "buffalo bills",
    "buf": "buffalo bills",
}

nba_teams = {
    "hawks": "atlanta hawks",
    "atlanta hawks": "atlanta hawks",
    "atl hawks": "atlanta hawks",
    "boston celtics": "boston celtics",
    "celtics": "boston celtics",
    "bos celtics": "boston celtics",
    "76ers": "philadelphia 76ers",
    "sixers": "philadelphia 76ers",
    "philadelphia 76ers": "philadelphia 76ers",
    "phi 76ers": "philadelphia 76ers",
    "la clippers": "los angeles clippers",
    "clippers": "los angeles clippers",
    "lac": "los angeles clippers",
    "los angeles clippers": "los angeles clippers",
    "mavericks": "dallas mavericks",
    "dallas mavericks": "dallas mavericks",
    "dal": "dallas mavericks",
    "bucks": "milwaukee bucks",
    "milwaukee bucks": "milwaukee bucks",
    "mil": "milwaukee bucks",
    "magic": "orlando magic",
    "orlando magic": "orlando magic",
    "orl": "orlando magic",
    "lakers": "los angeles lakers",
    "los angeles lakers": "los angeles lakers",
    "la lakers": "los angeles lakers",
    "lal": "los angeles lakers",
    "trail blazers": "portland trail blazers",
    "portland trail blazers": "portland trail blazers",
    "blazers": "portland trail blazers",
    "por": "portland trail blazers",
    "pacers": "indiana pacers",
    "indiana pacers": "indiana pacers",
    "ind": "indiana pacers",
    "heat": "miami heat",
    "miami heat": "miami heat",
    "mia": "miami heat",
    "rockets": "houston rockets",
    "houston rockets": "houston rockets",
    "hou": "houston rockets",
    "thunder": "oklahoma city thunder",
    "oklahoma city thunder": "oklahoma city thunder",
    "okc": "oklahoma city thunder",
    "nuggets": "denver nuggets",
    "denver nuggets": "denver nuggets",
    "den": "denver nuggets",
    "jazz": "utah jazz",
    "utah jazz": "utah jazz",
    "uta": "utah jazz",
    "raptors": "toronto raptors",
    "toronto raptors": "toronto raptors",
    "tor": "toronto raptors",
    "nets": "brooklyn nets",
    "brooklyn nets": "brooklyn nets",
    "bkn": "brooklyn nets",
    "grizzlies": "memphis grizzlies",
    "memphis grizzlies": "memphis grizzlies",
    "mem": "memphis grizzlies",
    "pistons": "detroit pistons",
    "detroit pistons": "detroit pistons",
    "det": "detroit pistons",
    "hornets": "charlotte hornets",
    "charlotte hornets": "charlotte hornets",
    "cha": "charlotte hornets",
    "spurs": "san antonio spurs",
    "san antonio spurs": "san antonio spurs",
    "sa": "san antonio spurs",
    "bulls": "chicago bulls",
    "chicago bulls": "chicago bulls",
    "chi": "chicago bulls",
    "wizards": "washington wizards",
    "washington wizards": "washington wizards",
    "was": "washington wizards",
    "cavaliers": "cleveland cavaliers",
    "cleveland cavaliers": "cleveland cavaliers",
    "cle": "cleveland cavaliers",
    "kings": "sacramento kings",
    "sacramento kings": "sacramento kings",
    "sac": "sacramento kings",
    "knicks": "new york knicks",
    "new york knicks": "new york knicks",
    "nyk": "new york knicks",
    "pelicans": "new orleans pelicans",
    "new orleans pelicans": "new orleans pelicans",
    "no": "new orleans pelicans",
    "suns": "phoenix suns",
    "phoenix suns": "phoenix suns",
    "phx": "phoenix suns",
    "warriors": "golden state warriors",
    "golden state warriors": "golden state warriors",
    "gsw": "golden state warriors",
    "timberwolves": "minnesota timberwolves",
    "minnesota timberwolves": "minnesota timberwolves",
    "min": "minnesota timberwolves"
}

cfl_teams_dict = {
    "b.c. lions": "british columbia lions",
    "bc lions": "british columbia lions",
    "british columbia lions": "british columbia lions",
    "saskatchewan roughriders": "saskatchewan roughriders",
    "sas roughriders": "saskatchewan roughriders",
    "winnipeg blue bombers": "winnipeg blue bombers",
    "win blue bombers": "winnipeg blue bombers",
    "calgary stampeders": "calgary stampeders",
    "cal stampeders": "calgary stampeders",
    "ottawa redblacks": "ottawa redblacks",
    "ott redblacks": "ottawa redblacks",
    "toronto argonauts": "toronto argonauts",
    "tor argonauts": "toronto argonauts",
    "montreal alouettes": "montreal alouettes",
    "mon alouettes": "montreal alouettes",
    "hamilton tiger-cats": "hamilton tiger-cats",
    "ham tiger-cats": "hamilton tiger-cats",
    "edmonton elks": "edmonton elks",
    "edm elks": "edmonton elks",
    "hamilton tiger cats": "hamilton tiger-cats"
}

ncaa_football_teams = {
    "georgia bulldogs": "georgia",
    "auburn tigers": "auburn",
    "louisville ": "louisville ",
    "southern california": "usc",
    "north texas mean green": "north texas",
    "bethune cookman": "bethune cookman",
    "kennesaw state": "kennesaw state",
    "eastern washington": "eastern washington",
    "montana": "montana",
    "portland state": "portland state",
    "utah tech": "utah tech",
    "ab christian": "abilene christian",
    "elon": "elon",
    "delaware": "delaware",
    "morgan state": "morgan state",
    "idaho state": "idaho state",
    "alabama st": "alabama state",
    "alabama st.": "alabama state",
    "nicholls state": "nicholls state",
    "nicholls st": "nicholls state",
    "nicholls st.": "nicholls state",
    "brown": "brown",
    "e illinois": "eastern illinois",
    "c connecticut": "central connecticut",
    "north dakota": "north dakota",
    "norfolk st": "norfolk state",
    "norfolk st.": "norfolk state",
    "weber st": "weber state",
    "weber st.": "weber state",
    "central conn": "central connecticut",
    "long island": "long island",
    "cornell": "cornell",
    "lehigh": "lehigh",
    "holy cross": "holy cross",
    "yale": "yale",
    "columbia": "columbia",
    "stonehill": "stonehill",
    "davidson": "davidson",
    "marist": "marist",
    "harvard": "harvard",
    "pennsylvania": "pennsylvania",
    "weber state": "weber state",
    "lamar": "lamar",
    "stetson": "stetson",
    "montana state": "montana state",
    "illinois st": "illinois state",
    "illinois st.": "illinois state",
    "hampton": "hampton",
    "drake": "drake",
    "delaware st": "delaware state",
    "delaware st.": "delaware state",
    "north dakota state": "north dakota state",
    "south dakota state": "south dakota state",
    "robert morris": "robert morris",
    "youngstown state": "youngstown state",
    "n colorado": "northern colorado",
    "northern colorado": "northern colorado",
    "villanova": "villanova",
    "tarleton st": "tarleton state",
    "tarleton st.": "tarleton state",
    "tarleton state": "tarleton",
    "unc central": "north carolina central",
    "p-view a&m": "prairie view",
    "prairie view": "prairie view",
    "so illinois": "southern illinois",
    "mcneese st": "mcneese state",
    "mcneese st.": "mcneese state",
    "east tennessee state": "east tennessee state",
    "tennessee tech": "tennessee tech",
    "lindenwood": "lindenwood",
    "western illinois": "western illinois",
    "stephen faustin": "stephen f.austin",
    "northwestern state": "northwestern state",
    "houston christian": "houston christian",
    "tennessee martin": "tennessee martin",
    "abilene christian": "abilene christian",
    "eastern illinois": "eastern illinois",
    "charleston sou": "charleston southern",
    "charl southern": "charleston southern",
    "southern utah": "southern utah",
    "richmond": "richmond",
    "s illinois": "southern illinois",
    "cal poly": "cal poly",
    "austin peay": "austin peay",
    "lafayette": "lafayette",
    "duquesne": "duquesne",
    "idaho": "idaho",
    "samford": "samford",
    "western carolina": "western carolina",
    "eastern kentucky": "eastern kentucky",
    "vmi": "vmi",
    "morgan st": "morgan state",
    "morgan st.": "morgan state",
    "sacred heart": "sacred heart",
    "georgetown": "georgetown",
    "st thomas": "st thomas",
    "st. thomas": "st thomas",
    "south dakota": "south dakota",
    "florida a&m": "florida a&m",
    "rhode island": "rhode island",
    "indiana state": "indiana state",
    "idaho st": "idaho state",
    "idaho st.": "idaho state",
    "c arkansas": "central arkansas",
    "se missouri st": "se missouri st",
    "se missouri st.": "se missouri st",
    "alabama a&m": "alabama a&m",
    "bethune-cook": "bethune cookman",
    "steph f austin": "stephen f. austin",
    "alcorn st": "alcorn state",
    "alcorn st.": "alcorn state",
    "n-western st": "northwestern state",
    "n-western st.": "northwestern state",
    "w illinois": "western illinois",
    "incarnate word": "incarnate word",
    "n arizona": "northern arizona",
    "monmouth": "monmouth",
    "maine": "maine",
    "se louisiana": "se louisiana",
    "colgate": "colgate",
    "bryant": "bryant",
    "wofford": "wofford",
    "e kentucky": "eastern kentucky",
    "tennessee st": "tennessee state",
    "tennessee st.": "tennessee state",
    "e tenn st": "east tennessee state",
    "e tenn st.": "east tennessee state",
    "portland st": "portland state",
    "portland st.": "portland state",
    "northern iowa": "northern iowa",
    "liu brooklyn": "long island",
    "nc central": "nc central",
    "missouri st": "missouri st",
    "missouri st.": "missouri st",
    "howard": "howard",
    "ut san antonio roadrunners": "utsa",
    "mercer": "mercer",
    "albany": "albany",
    "buffalo bulls": "buffalo",
    "southern": "southern",
    "jacksonville state": "jacksonville state",
    "j-ville st": "jacksonville state",
    "j-ville st.": "jacksonville state",
    "jackson st": "jacksonville state",
    "jackson st.": "jacksonville state",
    "jackson state": "jacksonville state",
    "arkansas st": "arkansas state",
    "arkansas st.": "arkansas state",
    "n alabama": "north alabama",
    "north alabama": "north alabama",
    "kansas st": "kansas state",
    "kansas st.": "kansas state",
    "charlotte": "charlotte",
    "ohio state buckeyes": "ohio state",
    "ohio st": "ohio state",
    "ohio st.": "ohio state",
    "appalachian st": "appalachian state",
    "appalachian st.": "appalachian state",
    "clemson tigers": "clemson",
    "clemson": "clemson",
    "wake forest demon deacons": "wake forest",
    "wake forest": "wake forest",
    "coastal c": "coastal carolina",
    "kansas": "kansas",
    "md b": "md baltimore co",
    "duke": "duke",
    "duke blue devils": "duke",
    "colorado buffaloes": "colorado",
    "usc trojans": "usc",
    "east carolina pirates": "east carolina",
    "cincinnati bearcats": "cincinnati",
    "fla gulf coast": "fla gulf coast",
    "central arkansas": "central arkansas",
    "albany ny": "albany ny",
    "va commonwe": "va commonwealth",
    "notre dame fighting irish": "notre dame",
    "notre dame": "notre dame",
    "georgia tech": "georgia tech",
    "florida st": "florida state",
    "florida st.": "florida state",
    "syracuse": "syracuse",
    "north carolina": "north carolina",
    "tx san antonio": "utsa",
    "texas san antonio": "utsa",
    "texas-san antonio": "utsa",
    "texas sa": "utsa",
    "texas state": "texas state",
    "tulane green wave": "tulane",
    "tulane": "tulane",
    "alabama": "alabama",
    "louisiana-lafayette ragin cajuns": "ul lafayette",
    "ul lafayette": "ul lafayette",
    "iowa state cyclones": "iowa state",
    "iowa st": "iowa state",
    "iowa st.": "iowa state",
    "ul monroe": "ul monroe",
    "army": "army",
    "utep miners": "utep",
    "utep": "utep",
    "texas": "texas",
    "w kentucky": "western kentucky",
    "louisville": "louisville",
    "mississippi st": "mississippi state",
    "mississippi st.": "mississippi state",
    "boston coll": "boston college",
    "boston college eagles": "boston college",
    "va tech": "virginia tech",
    "n mexico st": "new mexico state",
    "n mexico st.": "new mexico state",
    "arizona": "arizona",
    "fresno state bulldogs": "fresno state",
    "fresno st": "fresno state",
    "fresno st.": "fresno state",
    "oregon state beavers": "oregon state",
    "oregon st": "oregon state",
    "oregon st.": "oregon state",
    "washington st": "washington state",
    "washington st.": "washington state",
    "wisconsin badgers": "wisconsin",
    "wisconsin": "wisconsin",
    "mid tenn st": "middle tennessee state",
    "mid tenn st.": "middle tennessee state",
    "middle tenn": "middle tennessee state",
    "middle tennessee blue raiders": "middle tennessee state",
    "colorado st": "colorado state",
    "colorado st.": "colorado state",
    "akron zips": "akron",
    "michigan st": "michigan state",
    "michigan st.": "michigan state",
    "illinois fighting illini": "illinois",
    "unlv rebels": "unlv",
    "california golden bears": "california",
    "ucf": "central florida",
    "c florida": "central florida",
    "boise st": "boise state",
    "boise st.": "boise state",
    "new mexico lobos": "new mexico",
    "n carolina": "north carolina",
    "georgia st": "georgia state",
    "georgia st.": "georgia state",
    "penn": "penn state",
    "utsa": "utsa",
    "southern miss golden eagles": "southern miss",
    "miami (fl) hurricanes": "miami florida",
    "northwestern wildcats": "northwestern",
    "missouri tigers": "missouri",
    "s carolina": "south carolina",
    "so alabama": "south alabama",
    "c michigan": "central michigan",
    "central michigan chippewas": "central michigan",
    "w michigan": "western michigan",
    "western michigan broncos": "western michigan",
    "ball state cardinals": "ball state",
    "marshall": "marshall",
    "maryland terrapins": "maryland",
    "tennessee": "tennessee",
    "pittsburgh": "pittsburgh",
    "memphis tigers": "memphis",
    "navy": "navy",
    "colorado": "colorado",
    "air force falcons": "air force",
    "texas a&m": "texas a&m",
    "houston cougars": "houston",
    "texas tech red raiders": "texas tech",
    "iowa": "iowa",
    "old dominion": "old dominion",
    "e carolina": "east carolina",
    "w virginia": "west virginia",
    "uab": "uab",
    "liberty": "liberty",
    "kentucky": "kentucky",
    "florida": "florida",
    "u mass": "massachusetts",
    "toledo rockets": "toledo",
    "u conn": "connecticut",
    "kent st": "kent state",
    "kent st.": "kent state",
    "oklahoma": "oklahoma",
    "eastern michigan eagles": "eastern michigan",
    "n illinois": "northern illinois",
    "tulsa golden hurricane": "tulsa",
    "fiu": "florida international",
    "texas st": "texas state",
    "texas st.": "texas state",
    "san jose state": "san jose state",
    "auburn": "auburn",
    "georgia southern eagles": "georgia southern",
    "nebraska cornhuskers": "nebraska",
    "usc": "usc",
    "stanford cardinal": "stanford",
    "arizona st": "arizona state",
    "arizona st.": "arizona state",
    "oklahoma st": "oklahoma state",
    "oklahoma st.": "oklahoma state",
    "hawaii": "hawaii",
    "michigan wolverines": "michigan",
    "baylor bears": "baylor",
    "byu": "byu",
    "Brigham Young": "byu",
    "brigham young": "byu",
    "central florida": "central florida",
    "boise state": "boise state",
    "south carolina": "south carolina",
    "kansas state wildcats": "kansas state",
    "penn state": "penn state",
    "georgia state": "georgia state",
    "arkansas state": "arkansas state",
    "ohio state buckeyes": "ohio state",
    "miami florida": "miami florida",
    "south alabama": "south alabama",
    "central michigan": "central michigan",
    "western michigan": "western michigan",
    "ball state": "ball state",
    "washington state": "washington state",
    "appalachian state": "appalachian state",
    "iowa state": "iowa state",
    "michigan state": "michigan state",
    "middle tennessee state": "middle tennessee state",
    "colorado state": "colorado state",
    "east carolina": "east carolina",
    "west virginia": "west virginia",
    "florida international": "florida international",
    "eastern michigan": "eastern michigan",
    "kent state": "kent state",
    "northern illinois": "northern illinois",
    "massachusetts": "massachusetts",
    "connecticut": "connecticut",
    "indiana state": "indiana state",
    "san jose state": "san jose state",
    "georgia southern": "georgia southern",
    "arizona state": "arizona state",
    "oklahoma state": "oklahoma state",
    "boston college": "boston college",
    "virginia tech": "virginia tech",
    "new mexico state": "new mexico state",
    "oregon state": "oregon state",
    "fresno state": "fresno state",
    "mississippi state": "mississippi state",
    "new mexico state": "new mexico state",
    "florida state": "florida state",
    "wyoming": "wyoming",
    "cincinnati": "cincinnati",
    "miami ohio": "miami ohio",
    "miami": "miami florida",
    "purdue": "purdue",
    "western kentucky": "western kentucky",
    "indiana": "indiana",
    "georgia": "georgia",
    "buffalo": "buffalo",
    "coastal carolina": "coastal carolina",
    "ucla": "ucla",
    "rutgers": "rutgers",
    "temple": "temple",
    "north texas": "north texas",
    "mississippi": "mississippi",
    "troy": "troy",
    "oregon": "oregon state",
    "minnesota": "minnesota",
    "bowling green": "bowling green",
    "lsu": "lsu",
    "louisiana state": "lsu",
    "nc state": "nc state",
    "florida atlantic": "florida atlantic",
    "south florida": "south florida",
    "smu": "smu",
    "washington": "washington",
    "nevada": "nevada",
    "rice": "rice",
    "louisiana tech": "louisiana tech",
    "san diego state": "san diego state",
    "utah": "utah",
    "san diego state": "san diego state",
    "nc state": "nc state",
    "coastal carolina": "coastal carolina",
    "bucknell": "bucknell",
    "towson": "towson",
    "murray st": "murray st",
    "murray st.": "murray st",
    "stony brook": "stony brook",
    "tennessee martin": "tennessee martin",
    "campbell": "campbell",
    "n. carolina a & t": "n. carolina a & t",
    "tcu": "tcu",
    "james madison": "james madison",
    "utah state": "utah state",
    "florida atlantic": "florida atlantic",
    "louisiana tech": "louisiana tech",
    "north texas": "north texas",
    "bowling green": "bowling green",
    "south florida": "south florida",
    "coastal carolina": "coastal carolina",
    "chattanooga": "chattanooga",
    "fordham": "fordham",
    "texas southern": "texas southern",
    "florida international": "florida international",
    "cs sacramento": "cs sacramento",
    "houston baptist": "houston baptist",
    "ul lafayette": "ul lafayette",
    "florida atlantic": "florida atlantic",
    "nc state": "nc state",
    "so carolina st": "so carolina st",
    "so carolina st.": "so carolina st",
    "wagner": "wagner",
    "the citadel": "the citadel",
    "new hampshire": "new hampshire",
    "gardner webb": "gardner webb",
    "sam houston st": "sam houston st",
    "sam houston st.": "sam houston st"
}

ncaa_basketball_teams = {
    "texas-san antonio": "texas san antonio",
    "seattle": "seattle u",
    "texas arlington": "ut arlington",
    "colorado": "colorado",
    "brigham young": "byu",
    "miami florida": "miami florida",
    "miami-florida": "miami florida",
    "tennessee st.": "tennessee state",
    "wyoming ": "wyoming ",
    "texas a&m corpus": "texas a&m corpus christi",
    "middle tennessee state": "middle tenn st",
    "md b": "md baltimore co",
    "utah u": "utah",
    "ole miss": "mississippi",
    "lindenwood": "lindenwood",
    "southern indiana": "southern indiana",
    "queens nc": "queens nc",
    "n. carolina a&t": "north carolina a&t",
    "north carolina a&t": "north carolina a&t",
    "north carolina at": "north carolina a&t",
    "north carolina a t": "north carolina a&t",
    "central connecticut": "central connecticut",
    "tex a&m commerce": "tex a&m commerce",
    "mt. st. mary's": "mt. st. mary's",
    "fla gulf coast": "florida gulf coast",
    "central arkansas": "central arkansas",
    "arkansas": "arkansas state",
    "albany ny": "albany ny",
    "va commonwe": "va commonwealth",
    "george washington": "george washington",
    "le moyne": "le moyne dolphins",
    "yale": "yale",
    "stonehill": "stonehill",
    "bethune-cook": "bethune cookman",
    "bethune-cookman": "bethune cookman",
    "bethune cookman": "bethune cookman",
    "hcu": "houston christian",
    "princeton": "princeton",
    "cornell": "cornell",
    "pennsylvania": "pennsylvania",
    "columbia": "columbia",
    "harvard": "harvard",
    "nc wilmington": "nc wilmington",
    "indiana-purdue (iupui)": "iupui",
    "texas arlington": "ut arlington",
    "dartmouth": "dartmouth",
    "maryland-baltimore (umbc)": "nc greensboro",
    "coll charleston": "coll of charleston",
    "college of charleston (sc)": "coll of charleston",
    "jackson state (mississippi)": "jackson state",
    "charleston southern (sc)": "charleston sou",
    "alcorn state": "alcorn state",
    "mcneese state": "mcneese state",
    "utep (texas el-paso)": "utep",
    "rio grande valley (texas)": "ut rio grande valley",
    "texas rio grande valley": "ut rio grande valley",
    "texas san antonio (utsa)": "texas san antonio",
    "tarleton state": "tarleton st",
    "nc charlotte (uncc)": "charlotte u",
    "st. mary's (california)": "saint marys ca",
    "st. mary's california": "saint marys ca",
    "mary": "saint marys ca",
    "portland university": "portland",
    "north carolina st": "nc state",
    "st marys ca": "saint marys ca",
    "uc santa barbara": "cal santa barbara",
    "coastal carolina (sc)": "coastal carolina",
    "montana university": "montana",
    "southern u. (la)": "southern",
    "byu (cougars)": "byu",
    "vanderbilt (commodores)": "vanderbilt",
    "south florida (bulls)": "south florida",
    "hawaii (warriors)": "hawaii",
    "st. johns": "st. johns",
    "liberty (va)": "liberty",
    "wagner (ny)": "wagner",
    "st johns": "st. johns",
    "stephen austin": "stephen f. austin",
    "stephen f austin": "stephen f. austin",
    "stephen f. austin": "stephen f. austin",
    "new mexico st.": "new mexico state", 
    "mount st marys": "mount st marys",
    "mount st. marys": "mount st marys",
    "chicago state": "chicago state",
    "tx san antonio": "texas san antonio",
    "oregon st": "oregon state",
    "oregon st.": "oregon state",
    "omaha": "nebraska omaha",
    "toledo": "toledo",
    "marshall": "marshall",
    "pittsburgh": "pittsburgh",
    "miami florida": "miami florida",
    "san diego": "san diego",
    "cal poly": "cal poly slo",
    "mercer": "mercer",
    "georgia st": "georgia state",
    "georgia st.": "georgia state",
    "ohio st": "ohio state",
    "ohio st.": "ohio state",
    "purdue": "purdue",
    "cincinnati": "cincinnati",
    "cincy o128.5'": "cincinnati",
    "memphis": "memphis",
    "tulane": "tulane",
    "butler": "butler",
    "villanova": "villanova",
    "samford": "samford",
    "troy": "troy",
    "n colorado": "no. colorado",
    "denver": "denver",
    "oral roberts": "oral roberts",
    "oral": "oral roberts",
    "east carolina": "east carolina",
    "smu": "smu",
    "southern methodist": "smu",
    "tennessee tech": "tennessee tech",
    "j-ville st": "jacksonville state",
    "j-ville st.": "jacksonville state",
    "duke": "duke",
    "notre dame": "notre dame",
    "tcu": "tcu",
    "texas christian": "tcu",
    "oklahoma": "oklahoma state",
    "oklahoma st": "oklahoma state",
    "oklahoma st.": "oklahoma state",
    "utep": "utep",
    "arizona st": "arizona state",
    "arizona st.": "arizona state",
    "washington": "washington",
    "north dakota": "north dakota",
    "s illinois": "southern illinois",
    "s ill": "southern illinois",
    "thomas": "st. thomas (minn.)",
    "thomas": "st. thomas minn",
    "creighton": "creighton",
    "saint josephs": "st. josephs",
    "drexel": "drexel",
    "kansas": "kansas state",
    "texas tech": "texas tech",
    "seton hall": "seton hall",
    "marquette": "marquette",
    "dixie st": "dixie state",
    "dixie st.": "dixie state",
    "southern utah": "southern utah",
    "uc irvine": "cal irvine",
    "lmu": "loyola marymount",
    "san francisco": "san francisco",
    "oregon": "oregon",
    "nc state": "nc state",
    "st louis": "saint louis",
    "saint louis": "saint louis",
    "st. louis": "saint louis",
    "liu brooklyn": "long island",
    "sacred heart": "sacred heart",
    "bryant": "bryant",
    "delaware st": "delaware state",
    "delaware st.": "delaware state",
    "coastal car": "coastal carolina",
    "jackson st": "jackson state",
    "jackson st.": "jackson state",
    "bradley": "bradley",
    "houston bapt": "houston baptist",
    "north texas": "north texas",
    "e washington": "eastern washington",
    "n arizona": "northern arizona",
    "c michigan": "central michigan",
    "w michigan": "west michigan",
    "fairfield": "fairfield",
    "niagara": "niagara",
    "san diego st": "san diego state",
    "san diego st.": "san diego state",
    "saint peters": "st. peter's",
    "saint peter's": "st. peter's",
    "monmouth": "monmouth",
    "monmouth-nj": "monmouth",
    "monmouth nj": "monmouth",
    "siu e-ville": "siu edwardsville",
    "morehead st": "morehead state",
    "morehead st.": "morehead state",
    "drake": "drake",
    "south dakota": "south dakota",
    "davidson": "davidson",
    "rhode island": "rhode island",
    "belmont": "belmont",
    "iona": "iona",
    "rider": "rider",
    "chicago st": "chicago state",
    "chicago st.": "chicago state",
    "n illinois": "northern illinois",
    "w carolina": "west carolina",
    "charleston": "college of charleston",
    "tennessee": "tennessee",
    "ut martin": "tennessee martin",
    "tenn-martin": "tennessee martin",
    "tenn martin": "tennessee martin",
    "se missouri st": "se missouri state",
    "se missouri st.": "se missouri state",
    "santa clara": "santa clara",
    "clara": "santa clara",
    "san jose st": "san jose state",
    "san jose st.": "san jose state",
    "san jose state": "san jose state",
    "jose": "san jose state",
    "montana st": "montana state",
    "montana st.": "montana state",
    "washington st": "washington state",
    "washington st.": "washington state",
    "idaho": "idaho",
    "utah": "utah",
    "iowa st": "iowa state",
    "iowa st.": "iowa state",
    "w virginia": "west virginia",
    "west virginia": "west virginia",
    "utah st": "utah state",
    "utah st.": "utah state",
    "air force": "air force",
    "csu": "colorado state",
    "nevada": "nevada",
    "weber st": "weber state",
    "weber st.": "weber state",
    "portland state": "portland",
    "portland st": "portland state",
    "portland st.": "portland state",
    "loyola chi": "loyola chicago",
    "loyola chicago": "loyola chicago",
    "loyola-chicago": "loyola chicago",
    "richmond": "richmond",
    "unc wilmington": "nc wilmington",
    "norfolk st": "norfolk state",
    "norfolk st.": "norfolk state",
    "hampton": "hampton",
    "howard": "howard",
    "s carolina st": "south carolina state",
    "s carolina st.": "south carolina state",
    "presbyterian": "presbyterian",
    "n-western st": "north western state",
    "n-western st.": "north western state",
    "tulsa": "tulsa",
    "florida a&m": "florida a&m",
    "georgia tech": "georgia tech",
    "indiana": "indiana state",
    "gonzaga": "gonzaga",
    "iowa": "iowa",
    "louisville": "louisville",
    "wisconsin": "wisconsin",
    "auburn": "auburn",
    "the citadel": "the citadel",
    "longwood": "longwood",
    "unc greensboro": "nc greensboro",
    "elon": "elon",
    "elon university": "elon",
    "ball st": "ball state",
    "ball st.": "ball state",
    "indiana st": "indiana state",
    "indiana st.": "indiana state",
    "james madison": "james madison",
    "wright st": "wright state",
    "wright st.": "wright state",
    "detroit": "detroit",
    "valparaiso": "valparaiso",
    "valpo": "valparaiso",
    "youngstown st": "youngstown state",
    "youngstown st.": "youngstown state",
    "n kentucky": "northern kentucky",
    "milwaukee": "wisc milwaukee",
    "green bay": "wisc green bay",
    "hofstra": "hofstra",
    "st bonaventure": "st. bonaventure",
    "st. bonaventure": "st. bonaventure",
    "marist": "marist",
    "manhattan": "manhattan",
    "w kentucky": "west kentucky",
    "alabama": "alabama",
    "north carolina": "north carolina",
    "kentucky wildcats": "kentucky",
    "texas st": "texas state",
    "texas st.": "texas state",
    "stony brook": "stony brook",
    "binghamton": "binghamton",
    "lamar": "lamar",
    "louisiana tech": "louisiana tech",
    "fairleigh dickinson": "fairleigh dickinson",
    "maine": "maine",
    "hartford": "hartford",
    "grambling st": "grambling",
    "grambling st.": "grambling",
    "grambling state ": "grambling",
    "high point": "high point",
    "william & mary": "william mary",
    "dayton": "dayton",
    "chattanooga": "chattanooga",
    "uab": "uab",
    "ul monroe": "ul - monroe",
    "southern ms": "southern miss",
    "portland": "portland",
    "rice": "rice",
    "sam houston": "sam houston st",
    "sam houston st.": "sam houston st",
    "south alabama": "south alabama",
    "alabama a&m": "alabama am",
    "jacksonville": "jacksonville",
    "baylor": "baylor",
    "kansas st": "kansas state",
    "kansas st.": "kansas state",
    "umbc": "md baltimore co",
    "albany": "albany ny",
    "campbell": "campbell",
    "furman": "furman",
    "winthrop": "winthrop",
    "charlotte": "charlotte u",
    "ucla": "ucla",
    "delaware": "delaware",
    "la salle": "la salle",
    "kennesaw st": "kennesaw st",
    "kennesaw st.": "kennesaw st",
    "njit": "njit",
    "temple owls": "temple",
    "csun": "cs northridge",
    "california": "california",
    "coppin st": "coppin state",
    "coppin st.": "coppin state",
    "va tech": "virginia tech",
    "buffalo": "buffalo",
    "syracuse orange": "syracuse",
    "syracuse": "syracuse",
    "ucsb": "cal santa barbara",
    "pepperdine": "pepperdine",
    "oakland": "oakland",
    "uic": "illinois chicago",
    "Illinois-Chicago": "illinois chicago",
    "illinois-chicago": "illinois chicago",
    "ga southern": "georgia southern",
    "fiu": "florida international",
    "arizona": "arizona",
    "stanford": "stanford",
    "colorado st": "colorado state",
    "colorado st.": "colorado state",
    "saint mary's ca": "saint marys ca",
    "saint mary's": "saint marys ca",
    "miami ohio": "miami ohio",
    "miami oh": "miami ohio",
    "miami": "miami ohio",
    "georgia": "georgia",
    "radford": "radford",
    "missouri st": "missouri state",
    "missouri st.": "missouri state",
    "mcneese st": "mcneese state",
    "mcneese st.": "mcneese state",
    "louisiana": "ul - lafayette",
    "ucf knights": "central florida",
    "florida st": "florida state",
    "florida st.": "florida state",
    "cleveland st": "cleveland state",
    "cleveland st.": "cleveland state",
    "ipfw": "ipfw",
    "providence": "providence",
    "w illinois": "western illinois",
    "georgetown": "georgetown",
    "michigan st": "michigan state",
    "michigan st.": "michigan state",
    "northwestern": "northwestern",
    "grand canyon": "grand canyon",
    "minnesota": "minnesota",
    "alcorn st": "alcorn state",
    "alcorn st.": "alcorn state",
    "houston cougars": "houston",
    "new mexico": "new mexico",
    "boise st": "boise state",
    "boise st.": "boise state",
    "clemson": "clemson",
    "wofford": "wofford",
    "texas a&m commerce": "texas a&m",
    "vmi": "vmi",
    "george mason": "george mason",
    "e illinois": "eastern illinois",
    "evansville": "siu evansville",
    "arkansas-lr": "arkansas little rock",
    "murray st": "murray state",
    "murray st.": "murray state",
    "murray": "murray state",
    "austin peay": "austin",
    "csu b-field": "cs bakersfield",
    "new orleans": "new orleans",
    "massachusetts": "massachusetts",
    "vermont": "vermont",
    "umass lowell": "umass lowell",
    "charl southern": "charleston sou",
    "gardner-webb": "gardner webb",
    "ut rio grande valley": "ut rio grande valley",
    "p-view a&m": "prairie view am",
    "miss valley st": "mississippi valley state",
    "miss valley st.": "mississippi valley state",
    "mississippi st": "mississippi state",
    "mississippi st.": "mississippi state",
    "ark-pine bluff": "ark pine bluff",
    "texas southern": "texas southern",
    "appalachian st": "appalachian state",
    "appalachian st.": "appalachian state",
    "ohio": "ohio",
    "akron": "akron",
    "st. francis ny": "st. francis ny",
    "xavier": "xavier",
    "idaho st": "idaho state",
    "idaho st.": "idaho state",
    "towson": "towson",
    "rutgers": "rutgers",
    "se louisiana": "se louisiana",
    "southeastern louisiana": "se louisiana",
    "usc upstate": "usc upstate",
    "illinois": "illinois",
    "penn": "penn state",
    "depaul": "depaul",
    "umkc": "umkc",
    "kansas city": "umkc",
    "n-eastern": "northeastern",
    "c arkansas": "central arkansas",
    "lsu": "lsu",
    "louisiana state": "lsu",
    "e michigan": "eastern michigan",
    "usc": "usc",
    "southern california": "usc",
    "incarnate word": "incarnate word",
    "vcu": "vcu rams",
    "george wash": "george washington",
    "geo washington": "george washington",
    "fordham": "fordham",
    "central conn. st.": "central connecticut",
    "central conn st": "central connecticut",
    "bowling green": "bowling green",
    "unc asheville": "nc asheville",
    "fresno st": "fresno state",
    "fresno st.": "fresno state",
    "virginia": "virginia",
    "sc upstate": "usc upstate",
    "nebraska cornhuskers": "nebraska",
    "nebraska +0.5": "nebraska",
    "east tenn st": "east tenn state",
    "east tenn st.": "east tenn state",
    "east tennessee st.": "east tenn state",
    "e tenn st": "east tenn state",
    "e tenn st.": "east tenn state",
    "east": "east tennessee st",
    "arkansas": "arkansas",
    "boston college": "boston college",
    "e kentucky": "eastern kentucky",
    "connecticut": "connecticut",
    "missouri": "missouri state",
    "florida gators": "florida",
    "seattle": "seattle u",
    "sac state": "sacramento state",
    "sacramento st": "sacramento state",
    "sacramento st.": "sacramento state",
    "sacramento": "sacramento state",
    "michigan": "michigan",
    "maryland": "maryland",
    "canisius": "canisius",
    "iupui": "iupui",
    "lipscomb": "lipscomb",
    "ut arlington": "ut arlington",
    "texas-arlington": "ut arlington",
    "robert morris": "robert morris",
    "purdue fort wayne": "ipfw",
    "lb state": "long beach state",
    "long beach st": "long beach state",
    "long beach st.": "long beach state",
    "old dominion monarchs": "old dominion",
    "arkansas st": "arkansas state",
    "arkansas st.": "arkansas state",
    "kent st": "kent state",
    "kent st.": "kent state",
    "cs fullerton": "cs fullerton",
    "texas": "texas",
    "duquesne": "duquesne",
    "s carolina": "south carolina",
    "army": "army",
    "colgate": "colgate",
    "new hampshire": "new hampshire",
    "northern iowa": "northern iowa",
    "ab christian": "abilene christian",
    "north dakota st": "north dakota state",
    "north dakota st.": "north dakota state",
    "utah valley": "utah valley",
    "wichita st": "wichita state",
    "wichita st.": "wichita state",
    "nicholls st": "nicholls state",
    "nicholls st.": "nicholls state",
    "siena": "siena",
    "lehigh": "lehigh",
    "lafayette": "lafayette",
    "wake forest demon deacons": "wake forest",
    "wake forest": "wake forest",
    "navy midshipmen": "navy",
    "bucknell": "bucknell",
    "morgan st": "morgan state",
    "morgan st.": "morgan state",
    "boston u": "boston u",
    "holy cross": "holy cross",
    "alabama st": "alabama state",
    "alabama st.": "alabama state",
    "fau": "florida atlantic",
    "c connecticut": "central connecticut",
    "mt st marys": "mt. st. mary's",
    "mt st. marys": "mt. st. mary's",
    "st. francis pa": "st. francis pa",
    "merrimack": "merrimack",
    "unlv": "unlv",
    "hawaii": "hawaii",
    "uc riverside": "cal riverside",
    "quinnipiac": "quinnipiac",
    "illinois st": "illinois state",
    "illinois st.": "illinois state",
    "steph f austin": "stephen f austin",
    "tx a&m-cc": "texas a&m",
    "tx a&m-uc": "texas a&m",
    "texas a&m-cc": "texas a&m",
    "pacific": "pacific",
    "n alabama": "north alabama",
    "ut rg valley": "ut rio grande valley",
    "bellarmine": "bellarmine",
    "fl gulf coast": "fla gulf coast",
    "stetson": "stetson",
    "uc san diego": "uc san diego",
    "north florida": "north florida",
    "tarleton st": "tarleton st",
    "tarleton st.": "tarleton st",
    "cal baptist": "california baptist",
    "american": "american",
    "central michigan": "central michigan",
    "penn state": "penn state",
    "se missouri state": "se missouri state",
    "morehead state": "morehead state",
    "wichita state": "wichita state",
    "tennessee martin": "tennessee martin",
    "eastern kentucky": "eastern kentucky",
    "saint marys ca": "saint marys ca",
    "loyola marymount": "loyola marymount",
    "eastern illinois": "eastern illinois",
    "montana state": "montana state",
    "northern arizona": "northern arizona",
    "sacramento state": "sacramento state",
    "eastern washington": "eastern washington",
    "no. colorado": "no. colorado",
    "jacksonville state": "jacksonville state",
    "arizona state": "arizona state",
    "weber state": "weber state",
    "siu edwardsville": "siu edwardsville",
    "tennessee state": "tennessee state",
    "washington state": "washington state",
    "idaho state": "idaho state",
    "portland state": "portland state",
    "colorado state": "colorado state",
    "utah state": "utah state",
    "wright state": "wright state",
    "wright st.": "wright state",
    "illinois chicago": "illinois chicago",
    "youngstown state": "youngstown state",
    "wisc green bay": "wisc green bay",
    "georgia state": "georgia state",
    "appalachian state mountaineers": "appalachian state",
    "coastal carolina": "coastal carolina",
    "ball state": "ball state",
    "texas state": "texas state",
    "arkansas lr": "arkansas little rock",
    "ark little rock": "arkansas little rock",
    "northern kentucky": "northern kentucky",
    "st. peter's": "st. peter's",
    "florida international": "florida international",
    "charlotte u": "charlotte u",
    "florida atlantic": "florida atlantic",
    "cal poly slo": "cal poly slo",
    "cal irvine": "cal irvine",
    "cal santa barbara": "cal santa barbara",
    "cs bakersfield": "cs bakersfield",
    "cal riverside": "cal riverside",
    "arkansas state": "arkansas state",
    "ul - lafayette": "ul - lafayette",
    "ul lafayette": "ul - lafayette",
    "texas san antonio": "texas san antonio",
    "uc davis": "uc davis",
    "georgia southern": "georgia southern",
    "western illinois": "western illinois",
    "north dakota state": "north dakota state",
    "south dakota st": "south dakota state",
    "south dakota st.": "south dakota state",
    "south dakota state": "south dakota state",
    "south dakota": "south dakota",
    "wisc milwaukee": "wisc milwaukee",
    "cleveland state": "cleveland state",
    "dixie state": "dixie state",
    "fresno state": "fresno state",
    "boise state": "boise state",
    "san diego state": "san diego state",
    "central florida": "central florida",
    "oklahoma state": "oklahoma state",
    "florida state": "florida state",
    "kansas state": "kansas state",
    "east tenn state": "east tenn state",
    "ohio state": "ohio state",
    "western carolina": "western carolina",
    "western kentucky": "western kentucky",
    "middle tenn st": "middle tenn st",
    "middle tenn st.": "middle tenn st",
    "western michigan": "western michigan",
    "eastern michigan": "eastern michigan",
    "mississippi state": "mississippi state",
    "illinois state": "illinois state",
    "st. bonaventure": "st. bonaventure",
    "long beach state": "long beach state",
    "california baptist": "california baptist",
    "oregon state": "oregon state",
    "va commonwealth": "vcu",
    "indiana state": "indiana state",
    "iowa state": "iowa state",
    "southern illinois": "southern illinois",
    "southern": "southern",
    "st josephs": "st. josephs",
    "st. josephs": "st. josephs",
    "missouri state": "missouri state",
    "kent state": "kent state",
    "nc greensboro": "nc greensboro",
    "michigan state": "michigan state",
    "nebraska omaha": "nebraska omaha",
    "new mexico state": "new mexico state",
    "unc central": "north carolina central",
    "long island": "long island",
    "loyola md": "loyola maryland",
    "seattle u": "seattle u",
    "south dakota state": "south dakota state",
    "dakota": "south dakota coyotes",
    "northern illinois": "northern illinois",
    "northeastern": "northeastern",
    "north alabama": "north alabama",
    "abilene christian": "abilene christian",
    "brown": "brown",
    "florida intl": "florida intl",
    "ul - monroe": "ul - monroe",
    "tennessee tech (eagles)": "tennessee tech",
    "morgan state": "morgan state",
    "coppin state": "coppin state",
    "norfolk state": "norfolk state",
    "delaware state": "delaware state",
    "umes": "md eastern shore",
    "md eastern shore": "md eastern shore",
    "maryland-eastern shore": "md eastern shore",
    "maryland eastern shore": "md eastern shore",
    "south carolina state": "south carolina state",
    "north carolina central": "north carolina central",
    "grambling": "grambling",
    "ark pine bluff": "ark pine bluff",
    "jackson state": "jackson state",
    "mississippi valley state": "mississippi valley state",
    "alabama state": "alabama state",
    "loyola maryland": "loyola maryland",
    "charleston sou": "charleston sou",
    "gardner webb": "gardner webb",
    "prairie view a&m": "prairie view a&m",
    "houston baptist": "houston baptist",
    "northwestern state": "northwestern state",
    "st mary`s california": "saint marys ca",
    "st. mary`s california": "saint marys ca",
    "e. washington": "eastern washington",
    "washington u": "washington",
    "fla atlantic": "florida atlantic",
    "texas a&m corpus": "texas a&m corpus",
    "cal santa barb": "cal santa barbara",
    "nc central": "north carolina central",
    "nicholls state": "nicholls state",
    "new orleans u": "new orleans",
    "st peters": "st peters",
    "st. peters": "st peters",
    "northern colorado": "no. colorado",
    "cal state fullerton": "cs fullerton",
    "middletennessee st": "middle tenn st",
    "middletennessee st.": "middle tenn st",
    "houston u": "houston",
    "memphis u": "memphis",
    "nc asheville": "nc asheville",
    "indiana u": "indiana",
    "jacksonville st": "jacksonville state",
    "jacksonville st.": "jacksonville state",
    "detroit u": "detroit",
    "portland u": "portland",
    "md baltimore co": "md baltimore co",
    "utah tech": "utah tech",
    "little rock": "arkansas little rock",
    "montana": "montana state",
    "wilmington": "nc wilmington",
    "carolina": "n. carolina a&t",
    "indy": "iu indy",
    "davis": "uc davis",
    "riverside": "uc riverside",
    "mexico": "new mexico state",
    "middle": "middle tenn. st.",
    "poly": "cal poly",
    "northridge": "cs northridge",
    "tulane": "tulane"
}

mlb_teams = {
    "national league all stars": "national league",
    "american league all stars": "american league",
    "national league": "national league",
    "american league": "american league",
    "tb rays": "tampa bay rays",
    "tampa bay rays": "tampa bay rays",
    "rays": "tampa bay rays",
    "tam rays": "tampa bay rays",
    "bay rays": "tampa bay rays",
    "toronto blue jays": "toronto blue jays",
    "tor blue jays": "toronto blue jays",
    "blue jays": "toronto blue jays",
    "bluejays": "toronto blue jays",
    "washington nationals": "washington nationals",
    "national": "washington nationals",
    "nationals": "washington nationals",
    "was nationals": "washington nationals",
    "baltimore orioles": "baltimore orioles",
    "bal orioles": "baltimore orioles",
    "orioles": "baltimore orioles",
    "boston red sox": "boston red sox",
    "red sox": "boston red sox",
    "bos red sox": "boston red sox",
    "redsox": "boston red sox",
    "new york yankees": "new york yankees",
    "york yankees": "new york yankees",
    "yankees": "new york yankees",
    "ny yankees": "new york yankees",
    "new york mets": "new york mets",
    "york mets": "new york mets",
    "ny mets": "new york mets",
    "mets": "new york mets",
    "philadelphia phillies": "philadelphia phillies",
    "phillies": "philadelphia phillies",
    "phi phillies": "philadelphia phillies",
    "cleveland indians": "cleveland indians",
    "indians": "cleveland indians",
    "cleveland guardians": "cleveland guardians",
    "cle guardians": "cleveland guardians",
    "cle indians": "cleveland indians",
    "detroit tigers": "detroit tigers",
    "tigers": "detroit tigers",
    "det tigers": "detroit tigers",
    "pittsburgh pirates": "pittsburgh pirates",
    "pit pirates": "pittsburgh pirates",
    "pirates": "pittsburgh pirates",
    "cincinnati reds": "cincinnati reds",
    "cin reds": "cincinnati reds",
    "reds": "cincinnati reds",
    "atlanta": "atlanta braves",
    "atlanta braves": "atlanta braves",
    "braves": "atlanta braves",
    "atl braves": "atlanta braves",
    "miami marlins": "miami marlins",
    "mia marlins": "miami marlins",
    "marlins": "miami marlins",
    "kansas city royals": "kansas city royals",
    "kc royals": "kansas city royals",
    "kan royals": "cleveland guardians",
    "city royals": "kansas city royals",
    "royals": "kansas city royals",
    "minnesota twins": "minnesota twins",
    "min twins": "minnesota twins",
    "twins": "minnesota twins",
    "milwaukee brewers": "milwaukee brewers",
    "mil brewers": "milwaukee brewers",
    "brewers": "milwaukee brewers",
    "chicago cubs": "chicago cubs",
    "chi cubs": "chicago cubs",
    "cubs": "chicago cubs",
    "texas rangers": "texas rangers",
    "tex rangers": "texas rangers",
    "rangers": "texas rangers",
    "col rockies": "colorado rockies",
    "colorado rockies": "colorado rockies",
    "rockies": "colorado rockies",
    "sea mariners": "seattle mariners",
    "seattle mariners": "seattle mariners",
    "mariners": "seattle mariners",
    "hou astros": "houston astros",
    "houston astros": "houston astros",
    "astros": "houston astros",
    "la dodgers": "los angeles dodgers",
    "los angeles dodgers": "los angeles dodgers",
    "dodgers": "los angeles dodgers",
    "los angeles angels": "los angeles angels",
    "la angels": "los angeles angels",
    "angels": "los angeles angels",
    "sd padres": "san diego padres",
    "san diego padres": "san diego padres",
    "padres": "san diego padres",
    "arizona dbacks": "arizona diamondbacks",
    "d-backs": "arizona diamondbacks",
    "arizona diamondbacks": "arizona diamondbacks",
    "dbacks": "arizona diamondbacks",
    "diamondbacks": "arizona diamondbacks",
    "oak athletics": "oakland athletics",
    "oakland athletics": "oakland athletics",
    "athletics": "oakland athletics",
    "sf giants": "san francisco giants",
    "san francisco giants": "san francisco giants",
    "giants": "san francisco giants",
    "chi white sox": "chicago white sox",
    "white sox": "chicago white sox",
    "chicago white sox": "chicago white sox",
    "st louis cardinals": "st. louis cardinals",
    "stl cardinals": "st. louis cardinals",
    "st. louis cardinals": "st. louis cardinals",
    "cardinals": "st. louis cardinals",
    # Abreviaturas adicionales
    "tb": "tampa bay rays",
    "tor": "toronto blue jays",
    "wsh": "washington nationals",
    "was": "washington nationals",
    "bal": "baltimore orioles",
    "bos": "boston red sox",
    "nyy": "new york yankees",
    "nym": "new york mets",
    "phi": "philadelphia phillies",
    "cle": "cleveland guardians",
    "det": "detroit tigers",
    "pit": "pittsburgh pirates",
    "cin": "cincinnati reds",
    "atl": "atlanta braves",
    "mia": "miami marlins",
    "kc": "kansas city royals",
    "min": "minnesota twins",
    "mil": "milwaukee brewers",
    "chi": "chicago cubs",
    "tex": "texas rangers",
    "col": "colorado rockies",
    "sea": "seattle mariners",
    "hou": "houston astros",
    "lad": "los angeles dodgers",
    "laa": "los angeles angels",
    "sd": "san diego padres",
    "ari": "arizona diamondbacks",
    "oak": "oakland athletics",
    "sfg": "san francisco giants",
    "cws": "chicago white sox",
    "stl": "st. louis cardinals",
}

wnba_teams = {
    "aces": "las vegas aces",
    "veg aces": "las vegas aces",
    "lv aces": "las vegas aces",
    "las vegas aces": "las vegas aces",
    "fever": "indiana fever",
    "ind fever": "indiana fever",
    "indiana fever": "indiana fever",
    "liberty": "new york liberty",
    "ny liberty": "new york liberty",
    "new york liberty": "new york liberty",
    "sky": "chicago sky",
    "chi sky": "chicago sky",
    "chicago sky": "chicago sky",
    "wings": "dallas wings",
    "dal wings": "dallas wings",
    "dallas wings": "dallas wings",
    "lynx": "minnesota lynx",
    "min lynx": "minnesota lynx",
    "minnesota lynx": "minnesota lynx",
    "mercury": "phoenix mercury",
    "pho mercury": "phoenix mercury",
    "phoenix mercury": "phoenix mercury",
    "sun": "connecticut sun",
    "con sun": "connecticut sun",
    "connecticut sun": "connecticut sun",
    "sparks": "los angeles sparks",
    "la sparks": "los angeles sparks",
    "los angeles sparks": "los angeles sparks",
    "mystics": "washington mystics",
    "was mystics": "washington mystics",
    "wash mystics": "washington mystics",
    "washington mystics": "washington mystics",
    "storm": "seattle storm",
    "sea storm": "seattle storm",
    "seattle storm": "seattle storm",
    "dream": "atlanta dream",
    "atl dream": "atlanta dream",
    "atlanta dream": "atlanta dream",
}

nhl_teams = {
    "bos": "boston bruins",
    "cbj": "columbus blue jackets",
    "tor": "toronto maple leafs",
    "tbl": "tampa bay lightning",
    "cgy": "calgary flames",
    "lak": "los angeles kings",
    "coyotes": "arizona coyotes",
    "stl": "st. louis blues",
    "col": "colorado avalanche",
    "dal": "dallas stars",
    "fla": "florida panthers",
    "nyr": "new york rangers",
    "mtl": "montreal canadiens",
    "nsh": "nashville predators",
    "nas": "nashville predators",
    "edm": "edmonton oilers",
    "pit": "pittsburgh penguins",
    "phi": "philadelphia flyers",
    "car": "carolina hurricanes",
    "det": "detroit red wings",
    "nyi": "new york islanders",
    "buf": "buffalo sabres",
    "sjs": "san jose sharks",
    "sjo": "san jose sharks",
    "njd": "new jersey devils",
    "ott": "ottawa senators",
    "min": "minnesota wild",
    "van": "vancouver canucks",
    "g knights": "vegas golden knights",
    "vgk": "vegas golden knights",
    "cal": "calgary flames",
    "ana": "anaheim ducks",
    "sea": "seattle kraken",
    "stl": "st. louis blues",
    "tb": "tampa bay lightning",
    "was": "washington capitals",
    "wpj": "winnipeg jets",
    "nj": "new jersey devils",
    "chi": "chicago blackhawks",
    "ari": "arizona coyotes",
    "clb": "columbus blue jackets",
    "sj": "san jose sharks",
    "wpg": "winnipeg jets",
    "mon": "montreal canadiens",
    "tam": "tampa bay lightning",
    "ana ducks": "anaheim ducks",
    "anaheim ducks": "anaheim ducks",
    "ny rangers": "new york rangers",
    "dal stars": "dallas stars",
    "ott senators": "ottawa senators",
    "fla panthers": "florida panthers",
    "flo panthers": "florida panthers",
    "tampa bay lightning": "tampa bay lightning",
    "tb lightning": "tampa bay lightning",
    "sj sharks": "san jose sharks",
    "phi flyers": "philadelphia flyers",
    "tor maple leafs": "toronto maple leafs",
    "los angeles kings": "los angeles kings",
    "la kings": "los angeles kings",
    "mon canadiens": "montreal canadiens",
    "st louis blues": "st. louis blues",
    "stl blues": "st. louis blues",
    "chi blackhawks": "chicago blackhawks",
    "chi black hawks": "chicago blackhawks",
    "buf sabres": "buffalo sabres",
    "min wild": "minnesota wild",
    "det redwings": "detroit red wings",
    "det red wings": "detroit red wings",
    "was capitals": "washington capitals",
    "nsh predators": "nashville predators",
    "nas predators": "nashville predators",
    "edm oilers": "edmonton oilers",
    "cgy flames": "calgary flames",
    "calgary flames": "calgary flames",
    "cal flames": "calgary flames",
    "seattle kraken": "seattle kraken",
    "sea kraken": "seattle kraken",
    "vg knights": "vegas golden knights",
    "vgs golden knights": "vegas golden knights",
    "ny islanders": "new york islanders",
    "car hurricanes": "carolina hurricanes",
    "col avalanche": "colorado avalanche",
    "nj devils": "new jersey devils",
    "bos bruins": "boston bruins",
    "clb blue jackets": "columbus blue jackets",
    "pit penguins": "pittsburgh penguins",
    "van canucks": "vancouver canucks",
    "win jets": "winnipeg jets",
    "ari coyotes": "arizona coyotes",
    "arizona coyotes": "arizona coyotes",
    "arizona coyote": "arizona coyotes",
    "arz coyotes": "arizona coyotes",
    "boston bruins": "boston bruins",
    "bruins": "boston bruins",
    "vancouver canucks": "vancouver canucks",
    "canucks": "vancouver canucks",
    "vegas golden knights": "vegas golden knights",
    "golden knights": "vegas golden knights",
    "ducks": "anaheim ducks",
    "kraken": "seattle kraken",
    "washington capitals": "washington capitals",
    "capitals": "washington capitals",
    "winnipeg jets": "winnipeg jets",
    "jets": "winnipeg jets",
    "columbus blue jackets": "columbus blue jackets",
    "blue jackets": "columbus blue jackets",
    "toronto maple leafs": "toronto maple leafs",
    "maple leafs": "toronto maple leafs",
    "lightning": "tampa bay lightning",
    "flames": "calgary flames",
    "kings": "los angeles kings",
    "coyotes": "arizona coyotes",
    "g knights": "vegas golden knights",
    "st. louis blues": "st. louis blues",
    "blues": "st. louis blues",
    "florida panthers": "florida panthers",
    "panthers": "florida panthers",
    "new york rangers": "new york rangers",
    "rangers": "new york rangers",
    "colorado avalanche": "colorado avalanche",
    "avalanche": "colorado avalanche",
    "pittsburgh penguins": "pittsburgh penguins",
    "penguins": "pittsburgh penguins",
    "philadelphia flyers": "philadelphia flyers",
    "flyers": "philadelphia flyers",
    "detroit red wings": "detroit red wings",
    "red wings": "detroit red wings",
    "carolina hurricanes": "carolina hurricanes",
    "hurricanes": "carolina hurricanes",
    "buffalo sabres": "buffalo sabres",
    "sabres": "buffalo sabres",
    "new york islanders": "new york islanders",
    "islanders": "new york islanders",
    "dallas stars": "dallas stars",
    "stars": "dallas stars",
    "edmonton oilers": "edmonton oilers",
    "oilers": "edmonton oilers",
    "san jose sharks": "san jose sharks",
    "sharks": "san jose sharks",
    "new jersey devils": "new jersey devils",
    "devils": "new jersey devils",
    "ottawa senators": "ottawa senators",
    "senators": "ottawa senators",
    "montreal canadiens": "montreal canadiens",
    "canadiens": "montreal canadiens",
    "minnesota wild": "minnesota wild",
    "wild": "minnesota wild",
    "nashville predators": "nashville predators",
    "predators": "nashville predators",
    "chicago blackhawks": "chicago blackhawks",
    "blackhawks": "chicago blackhawks"
}


def get_team_dictionary(sport):
    sport = sport.lower()
    if sport == "nfl":
        return nfl_teams
    elif sport == "nba":
        return nba_teams
    elif sport == "cfl":
        return cfl_teams_dict
    elif sport == "ncaaf":
        return ncaa_football_teams
    elif sport in ["ncaab", "ncaam"]:
        return ncaa_basketball_teams
    elif sport == "mlb":
        return mlb_teams
    elif sport == "wnba":
        return wnba_teams
    elif sport == "nhl":
        return nhl_teams
    return {}